In [1]:
import numpy as np
a=np.random.randn(5)

In [2]:
print(a)

[-1.24636878  0.9232378   1.08583195 -0.81245767  0.30735486]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.24636878  0.9232378   1.08583195 -0.81245767  0.30735486]


In [5]:
print(np.dot(a,a.T))

4.339388671902334


In [6]:
 a=np.random.rand(5,1)

In [7]:
print(a)

[[0.08479921]
 [0.50967487]
 [0.246323  ]
 [0.13306487]
 [0.80557785]]


In [8]:
print(a.T)

[[0.08479921 0.50967487 0.246323   0.13306487 0.80557785]]


In [9]:
print(np.dot(a,a.T))

[[0.00719091 0.04322003 0.020888   0.0112838  0.06831236]
 [0.04322003 0.25976847 0.12554464 0.06781982 0.41058278]
 [0.020888   0.12554464 0.06067502 0.03277694 0.19843236]
 [0.0112838  0.06781982 0.03277694 0.01770626 0.10719411]
 [0.06831236 0.41058278 0.19843236 0.10719411 0.64895567]]


In [10]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [11]:
print(c)

[[-0.16740235 -1.25829526 -3.72269796]
 [ 3.07073055 -0.47900926 -0.21309162]
 [-1.08626648  0.77207777 -0.25801575]]


In [13]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [ ]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]